name: Upload Lambda & Deploy Terraform

on:
  workflow_dispatch:
    inputs:
      files:
        description: "Files to deploy (comma separated, e.g., script1.py,script2.py). Leave empty to deploy all scripts."
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get files to deploy
        id: changed_files
        run: |
          if [ -n "${{ github.event.inputs.files }}" ]; then
            # Use input files from the user
            CHANGED_FILES="${{ github.event.inputs.files }}"
            CHANGED_FILES="${CHANGED_FILES//,/ }"
          else
            # No input given: deploy all Python scripts
            CHANGED_FILES=$(ls scripts/*.py)
          fi
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "Files to deploy: $CHANGED_FILES"

      - name: Zip scripts
        run: |
          mkdir -p zipped
          for file in $CHANGED_FILES; do
            if [ -f "$file" ]; then
              filename=$(basename "$file" .py)
              zip -j "zipped/${filename}.zip" "$file"
              echo "Zipped $file"
            else
              echo "File not found: $file"
            fi
          done

      - name: Upload ZIPs to S3
        run: |
          for zipfile in zipped/*.zip; do
            aws s3 cp "$zipfile" "s3://lambda-prod-artifacts-ziad/lambda/$(basename $zipfile)"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        working-directory: prod
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Terraform Apply
        working-directory: prod
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
